---
title: "A7"
author: "Zhirui Deng"
date: "2023-04-09"
output: html_document
---

**Task 1**

```{r message=F}
library(tidyverse)
library(data.table) ## For the fread function
library(lubridate)
source("sepsis_monitor_functions.R")
```

**Task 2**

```{r,warning=F,message=F}
library(tictoc)

# n=50
tic()
test1=makeSepsisDataset(n=50,read_fn = "fread")
print(paste0("n=50,fn=fdread"))
toc()

tic()
test1=makeSepsisDataset(n=50,read_fn = "read_delim")
print(paste0("n=50,fn=read_delim"))
toc()

# n=100
tic()
test1=makeSepsisDataset(n=100,read_fn = "fread")
print(paste0("n=100,fn=fdread"))
toc()

tic()
test1=makeSepsisDataset(n=100,read_fn = "read_delim")
print(paste0("n=100,fn=read_delim"))
toc()

# n=500
tic()
test1=makeSepsisDataset(n=500,read_fn = "fread")
print(paste0("n=500,fn=fdread"))
toc()

tic()
test1=makeSepsisDataset(n=500,read_fn = "read_delim")
print(paste0("n=500,fn=read_delim"))
toc()

```

**Task 3**

```{r message=F}
library(googledrive)
df <- makeSepsisDataset()

# We have to write the file to disk first, then upload it
df %>% write_csv("sepsis_data_temp.csv")

# Uploading happens here
sepsis_file <- drive_put(media = "sepsis_data_temp.csv", 
          path = "https://drive.google.com/drive/folders/1tPCDKc-Oe_129trh2D33mvY1vKd-1ZPd",
          name = "sepsis_data.csv")

# Set the file permissions so anyone can download this file.
sepsis_file %>% drive_share_anyone()

```

```{r message=F}
drive_deauth()
file_link <- "https://drive.google.com/file/d/14oM0-y0gwLSlny1Nl7_MZ39WJReLRoow"
## Data_all
new_data <- updateData(file_link)
## Data_most_recent
most_recent_data <- new_data %>%
  group_by(PatientID) %>%
  filter(obsTime == max(obsTime))
```




